// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjPQ3aCJ1GZEn8XqRDi5NXSLwUfOStLwA',
    appId: '1:941028966830:web:e1cd5b5f8f3dbd6717883f',
    messagingSenderId: '941028966830',
    projectId: 'restmap-bb3a1',
    authDomain: 'restmap-bb3a1.firebaseapp.com',
    storageBucket: 'restmap-bb3a1.appspot.com',
    measurementId: 'G-1MM6DKZNNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIn5DdAJpwokXprfTlvblSzRX7ZVvNGFU',
    appId: '1:941028966830:android:36c96fa9c78afc7917883f',
    messagingSenderId: '941028966830',
    projectId: 'restmap-bb3a1',
    storageBucket: 'restmap-bb3a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhNSQ3RJWdXa0otiAuO3v2g4Qqo-DTJxA',
    appId: '1:941028966830:ios:f5188ceb1945db5517883f',
    messagingSenderId: '941028966830',
    projectId: 'restmap-bb3a1',
    storageBucket: 'restmap-bb3a1.appspot.com',
    iosClientId: '941028966830-vippoq2jkli8m5m6pqanv3s7ok1s32ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.restmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhNSQ3RJWdXa0otiAuO3v2g4Qqo-DTJxA',
    appId: '1:941028966830:ios:f5188ceb1945db5517883f',
    messagingSenderId: '941028966830',
    projectId: 'restmap-bb3a1',
    storageBucket: 'restmap-bb3a1.appspot.com',
    iosClientId: '941028966830-vippoq2jkli8m5m6pqanv3s7ok1s32ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.restmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjPQ3aCJ1GZEn8XqRDi5NXSLwUfOStLwA',
    appId: '1:941028966830:web:0ca42c119d5ed8fc17883f',
    messagingSenderId: '941028966830',
    projectId: 'restmap-bb3a1',
    authDomain: 'restmap-bb3a1.firebaseapp.com',
    storageBucket: 'restmap-bb3a1.appspot.com',
    measurementId: 'G-5S9XEB937Q',
  );
}
