name: Flutter Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-analyze-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    - name: Navigate to Flutter project directory
      run: cd restmap

    - name: Install dependencies
      run: flutter pub get
      working-directory: restmap

    - name: Run Flutter Analyzer
      run: flutter analyze
      working-directory: restmap

    - name: Run Flutter Tests
      run: flutter test
      working-directory: restmap
