name: Flutter Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-analyze-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Analyzer
      run: flutter analyze

    - name: Run Flutter Tests
      run: flutter test
